import { Asset } from './types';

export const INITIAL_CASH = 10000;

export const ASSETS: Asset[] = [
  // Tech Stocks
  {
    id: 'tsla',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    type: 'stock',
    price: 248.50,
    change: 12.30,
    changePercent: 5.2,
  },
  {
    id: 'aapl',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    type: 'stock',
    price: 178.25,
    change: -2.10,
    changePercent: -1.2,
  },
  {
    id: 'nvda',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'stock',
    price: 485.90,
    change: 8.75,
    changePercent: 1.8,
  },
  {
    id: 'msft',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'stock',
    price: 378.50,
    change: 3.20,
    changePercent: 0.9,
  },
  {
    id: 'amzn',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    type: 'stock',
    price: 142.60,
    change: -1.80,
    changePercent: -1.2,
  },
  {
    id: 'meta',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    type: 'stock',
    price: 312.40,
    change: 5.60,
    changePercent: 1.8,
  },
  {
    id: 'googl',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'stock',
    price: 138.75,
    change: 2.15,
    changePercent: 1.6,
  },
  {
    id: 'nflx',
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    type: 'stock',
    price: 445.20,
    change: -8.30,
    changePercent: -1.8,
  },
  // Financial & Other Sectors
  {
    id: 'jpm',
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'stock',
    price: 154.85,
    change: 1.25,
    changePercent: 0.8,
  },
  {
    id: 'v',
    symbol: 'V',
    name: 'Visa Inc.',
    type: 'stock',
    price: 245.60,
    change: 3.40,
    changePercent: 1.4,
  },
  {
    id: 'jnj',
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    type: 'stock',
    price: 158.30,
    change: -0.85,
    changePercent: -0.5,
  },
  {
    id: 'pg',
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    type: 'stock',
    price: 162.45,
    change: 0.95,
    changePercent: 0.6,
  },
  {
    id: 'ko',
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    type: 'stock',
    price: 61.20,
    change: 0.35,
    changePercent: 0.6,
  },
  {
    id: 'dis',
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    type: 'stock',
    price: 96.55,
    change: -1.45,
    changePercent: -1.5,
  },
  // Energy Sector
  {
    id: 'xom',
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    type: 'stock',
    price: 105.40,
    change: 2.15,
    changePercent: 2.1,
  },
  {
    id: 'cvx',
    symbol: 'CVX',
    name: 'Chevron Corporation',
    type: 'stock',
    price: 148.90,
    change: 1.85,
    changePercent: 1.3,
  },
  // Healthcare Sector
  {
    id: 'unh',
    symbol: 'UNH',
    name: 'UnitedHealth Group Inc.',
    type: 'stock',
    price: 485.20,
    change: -3.40,
    changePercent: -0.7,
  },
  {
    id: 'pfe',
    symbol: 'PFE',
    name: 'Pfizer Inc.',
    type: 'stock',
    price: 28.75,
    change: 0.45,
    changePercent: 1.6,
  },
  {
    id: 'abbv',
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    type: 'stock',
    price: 157.60,
    change: 2.30,
    changePercent: 1.5,
  },
  // Consumer & Retail
  {
    id: 'wmt',
    symbol: 'WMT',
    name: 'Walmart Inc.',
    type: 'stock',
    price: 168.40,
    change: 1.25,
    changePercent: 0.8,
  },
  {
    id: 'hd',
    symbol: 'HD',
    name: 'The Home Depot Inc.',
    type: 'stock',
    price: 312.85,
    change: -2.60,
    changePercent: -0.8,
  },
  {
    id: 'mcd',
    symbol: 'MCD',
    name: "McDonald's Corporation",
    type: 'stock',
    price: 285.40,
    change: 3.15,
    changePercent: 1.1,
  },
  {
    id: 'nke',
    symbol: 'NKE',
    name: 'Nike Inc.',
    type: 'stock',
    price: 98.30,
    change: -1.90,
    changePercent: -1.9,
  },
  {
    id: 'sbux',
    symbol: 'SBUX',
    name: 'Starbucks Corporation',
    type: 'stock',
    price: 94.20,
    change: 0.85,
    changePercent: 0.9,
  },
  // Finance & Banking
  {
    id: 'bac',
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    type: 'stock',
    price: 33.45,
    change: 0.65,
    changePercent: 2.0,
  },
  {
    id: 'gs',
    symbol: 'GS',
    name: 'The Goldman Sachs Group Inc.',
    type: 'stock',
    price: 382.50,
    change: 4.20,
    changePercent: 1.1,
  },
  {
    id: 'ma',
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    type: 'stock',
    price: 412.30,
    change: 5.80,
    changePercent: 1.4,
  },
  {
    id: 'c',
    symbol: 'C',
    name: 'Citigroup Inc.',
    type: 'stock',
    price: 54.20,
    change: -0.85,
    changePercent: -1.5,
  },
  // Industrial & Manufacturing
  {
    id: 'ba',
    symbol: 'BA',
    name: 'The Boeing Company',
    type: 'stock',
    price: 192.40,
    change: -3.20,
    changePercent: -1.6,
  },
  {
    id: 'cat',
    symbol: 'CAT',
    name: 'Caterpillar Inc.',
    type: 'stock',
    price: 285.60,
    change: 2.40,
    changePercent: 0.8,
  },
  {
    id: 'ge',
    symbol: 'GE',
    name: 'General Electric Company',
    type: 'stock',
    price: 128.75,
    change: 1.95,
    changePercent: 1.5,
  },
  // Tech & Semiconductors
  {
    id: 'amd',
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc.',
    type: 'stock',
    price: 142.80,
    change: 3.60,
    changePercent: 2.6,
  },
  {
    id: 'intc',
    symbol: 'INTC',
    name: 'Intel Corporation',
    type: 'stock',
    price: 43.25,
    change: -0.75,
    changePercent: -1.7,
  },
  {
    id: 'crm',
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    type: 'stock',
    price: 264.90,
    change: 4.50,
    changePercent: 1.7,
  },
  {
    id: 'orcl',
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    type: 'stock',
    price: 112.40,
    change: 1.80,
    changePercent: 1.6,
  },
  {
    id: 'adbe',
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    type: 'stock',
    price: 582.30,
    change: -5.20,
    changePercent: -0.9,
  },
  // Telecom & Media
  {
    id: 't',
    symbol: 'T',
    name: 'AT&T Inc.',
    type: 'stock',
    price: 17.85,
    change: 0.25,
    changePercent: 1.4,
  },
  {
    id: 'vz',
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    type: 'stock',
    price: 40.65,
    change: -0.35,
    changePercent: -0.9,
  },
  {
    id: 'cmcsa',
    symbol: 'CMCSA',
    name: 'Comcast Corporation',
    type: 'stock',
    price: 42.90,
    change: 0.55,
    changePercent: 1.3,
  },
  // ETFs
  {
    id: 'spy',
    symbol: 'SPY',
    name: 'S&P 500 ETF Trust',
    type: 'etf',
    price: 448.30,
    change: 2.10,
    changePercent: 0.5,
  },
  {
    id: 'qqq',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    type: 'etf',
    price: 385.40,
    change: 4.20,
    changePercent: 1.1,
  },
  {
    id: 'dia',
    symbol: 'DIA',
    name: 'SPDR Dow Jones Industrial Average ETF',
    type: 'etf',
    price: 378.90,
    change: 1.85,
    changePercent: 0.5,
  },
  {
    id: 'iwm',
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    type: 'etf',
    price: 195.75,
    change: -1.20,
    changePercent: -0.6,
  },
  {
    id: 'tlt',
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    type: 'etf',
    price: 92.15,
    change: -0.45,
    changePercent: -0.5,
  },
  // Cryptocurrencies
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    price: 43250.00,
    change: 1820.00,
    changePercent: 4.4,
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    price: 2280.50,
    change: -65.30,
    changePercent: -2.8,
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    type: 'crypto',
    price: 98.75,
    change: 5.20,
    changePercent: 5.6,
  },
  {
    id: 'ada',
    symbol: 'ADA',
    name: 'Cardano',
    type: 'crypto',
    price: 0.52,
    change: 0.03,
    changePercent: 6.1,
  },
  {
    id: 'bnb',
    symbol: 'BNB',
    name: 'Binance Coin',
    type: 'crypto',
    price: 312.80,
    change: -8.40,
    changePercent: -2.6,
  },
  {
    id: 'xrp',
    symbol: 'XRP',
    name: 'Ripple',
    type: 'crypto',
    price: 0.61,
    change: 0.02,
    changePercent: 3.4,
  },
  // Commodities
  {
    id: 'xau',
    symbol: 'XAU',
    name: 'Gold',
    type: 'commodity',
    price: 2025.80,
    change: 8.40,
    changePercent: 0.4,
  },
  {
    id: 'xag',
    symbol: 'XAG',
    name: 'Silver',
    type: 'commodity',
    price: 24.15,
    change: 0.35,
    changePercent: 1.5,
  },
  {
    id: 'wti',
    symbol: 'WTI',
    name: 'Crude Oil',
    type: 'commodity',
    price: 78.45,
    change: -1.25,
    changePercent: -1.6,
  },
  {
    id: 'ng',
    symbol: 'NG',
    name: 'Natural Gas',
    type: 'commodity',
    price: 2.85,
    change: 0.08,
    changePercent: 2.9,
  },
];
