import { Asset, AssetType } from './types';

export const INITIAL_CASH = 100000; // $100,000 starting balance

export const ASSETS: Asset[] = [
  // ==========================================
  // MAJOR CRYPTOCURRENCIES (30+)
  // ==========================================
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    price: 105420.00, // 2026 estimate
    change: 2850.00,
    changePercent: 2.78,
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    price: 3850.00, // 2026 estimate
    change: 125.50,
    changePercent: 3.37,
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    type: 'crypto',
    price: 248.50, // 2026 estimate
    change: 14.80,
    changePercent: 6.33,
  },
  {
    id: 'bnb',
    symbol: 'BNB',
    name: 'BNB',
    type: 'crypto',
    price: 312.80,
    change: -8.50,
    changePercent: -2.65,
  },
  {
    id: 'xrp',
    symbol: 'XRP',
    name: 'XRP',
    type: 'crypto',
    price: 0.6245,
    change: 0.0285,
    changePercent: 4.78,
  },
  {
    id: 'ada',
    symbol: 'ADA',
    name: 'Cardano',
    type: 'crypto',
    price: 0.5820,
    change: -0.0180,
    changePercent: -3.00,
  },
  {
    id: 'doge',
    symbol: 'DOGE',
    name: 'Dogecoin',
    type: 'crypto',
    price: 0.0825,
    change: 0.0045,
    changePercent: 5.77,
  },
  {
    id: 'avax',
    symbol: 'AVAX',
    name: 'Avalanche',
    type: 'crypto',
    price: 38.90,
    change: 2.15,
    changePercent: 5.85,
  },
  {
    id: 'dot',
    symbol: 'DOT',
    name: 'Polkadot',
    type: 'crypto',
    price: 7.85,
    change: -0.22,
    changePercent: -2.73,
  },
  {
    id: 'matic',
    symbol: 'MATIC',
    name: 'Polygon',
    type: 'crypto',
    price: 0.8950,
    change: 0.0420,
    changePercent: 4.92,
  },
  {
    id: 'link',
    symbol: 'LINK',
    name: 'Chainlink',
    type: 'crypto',
    price: 14.85,
    change: 0.65,
    changePercent: 4.58,
  },
  {
    id: 'ltc',
    symbol: 'LTC',
    name: 'Litecoin',
    type: 'crypto',
    price: 72.40,
    change: -1.80,
    changePercent: -2.43,
  },
  // Additional Cryptocurrencies (18 more)
  {
    id: 'shib',
    symbol: 'SHIB',
    name: 'Shiba Inu',
    type: 'crypto',
    price: 0.00001245,
    change: 0.00000085,
    changePercent: 7.32,
  },
  {
    id: 'uni',
    symbol: 'UNI',
    name: 'Uniswap',
    type: 'crypto',
    price: 6.82,
    change: 0.28,
    changePercent: 4.28,
  },
  {
    id: 'atom',
    symbol: 'ATOM',
    name: 'Cosmos',
    type: 'crypto',
    price: 9.45,
    change: 0.32,
    changePercent: 3.51,
  },
  {
    id: 'algo',
    symbol: 'ALGO',
    name: 'Algorand',
    type: 'crypto',
    price: 0.1890,
    change: -0.0065,
    changePercent: -3.32,
  },
  {
    id: 'ftm',
    symbol: 'FTM',
    name: 'Fantom',
    type: 'crypto',
    price: 0.4250,
    change: 0.0285,
    changePercent: 7.19,
  },
  {
    id: 'near',
    symbol: 'NEAR',
    name: 'NEAR Protocol',
    type: 'crypto',
    price: 3.85,
    change: 0.22,
    changePercent: 6.06,
  },
  {
    id: 'icp',
    symbol: 'ICP',
    name: 'Internet Computer',
    type: 'crypto',
    price: 12.45,
    change: -0.85,
    changePercent: -6.39,
  },
  {
    id: 'xlm',
    symbol: 'XLM',
    name: 'Stellar',
    type: 'crypto',
    price: 0.1285,
    change: 0.0045,
    changePercent: 3.63,
  },
  {
    id: 'vet',
    symbol: 'VET',
    name: 'VeChain',
    type: 'crypto',
    price: 0.0285,
    change: 0.0012,
    changePercent: 4.40,
  },
  {
    id: 'fil',
    symbol: 'FIL',
    name: 'Filecoin',
    type: 'crypto',
    price: 5.85,
    change: 0.32,
    changePercent: 5.79,
  },
  {
    id: 'hbar',
    symbol: 'HBAR',
    name: 'Hedera',
    type: 'crypto',
    price: 0.0785,
    change: 0.0028,
    changePercent: 3.70,
  },
  {
    id: 'apt',
    symbol: 'APT',
    name: 'Aptos',
    type: 'crypto',
    price: 9.25,
    change: 0.65,
    changePercent: 7.56,
  },
  {
    id: 'arb',
    symbol: 'ARB',
    name: 'Arbitrum',
    type: 'crypto',
    price: 1.12,
    change: 0.08,
    changePercent: 7.69,
  },
  {
    id: 'op',
    symbol: 'OP',
    name: 'Optimism',
    type: 'crypto',
    price: 2.45,
    change: 0.18,
    changePercent: 7.93,
  },
  {
    id: 'inj',
    symbol: 'INJ',
    name: 'Injective',
    type: 'crypto',
    price: 28.50,
    change: 2.15,
    changePercent: 8.16,
  },
  {
    id: 'sui',
    symbol: 'SUI',
    name: 'Sui',
    type: 'crypto',
    price: 1.45,
    change: 0.12,
    changePercent: 9.02,
  },
  {
    id: 'sei',
    symbol: 'SEI',
    name: 'Sei',
    type: 'crypto',
    price: 0.52,
    change: 0.04,
    changePercent: 8.33,
  },
  {
    id: 'tia',
    symbol: 'TIA',
    name: 'Celestia',
    type: 'crypto',
    price: 12.85,
    change: 1.15,
    changePercent: 9.83,
  },
  // ==========================================
  // TECHNOLOGY STOCKS (40+)
  // ==========================================
  {
    id: 'aapl',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    type: 'stock',
    price: 185.92,
    change: 2.45,
    changePercent: 1.34,
  },
  {
    id: 'msft',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'stock',
    price: 378.91,
    change: 4.82,
    changePercent: 1.29,
  },
  {
    id: 'googl',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'stock',
    price: 335.00, // 2026 Truth Sheet value
    change: 4.25,
    changePercent: 1.29,
  },
  {
    id: 'amzn',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    type: 'stock',
    price: 178.25,
    change: -2.15,
    changePercent: -1.19,
  },
  {
    id: 'nvda',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'stock',
    price: 142.50, // 2026 estimate post-split adjusted
    change: 3.85,
    changePercent: 2.78,
  },
  {
    id: 'tsla',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    type: 'stock',
    price: 248.50,
    change: -5.30,
    changePercent: -2.09,
  },
  {
    id: 'meta',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    type: 'stock',
    price: 505.95,
    change: 8.45,
    changePercent: 1.70,
  },
  {
    id: 'nflx',
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    type: 'stock',
    price: 485.60,
    change: -3.20,
    changePercent: -0.65,
  },
  {
    id: 'amd',
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    type: 'stock',
    price: 142.30,
    change: 3.85,
    changePercent: 2.78,
  },
  {
    id: 'crm',
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    type: 'stock',
    price: 264.90,
    change: 4.50,
    changePercent: 1.73,
  },
  {
    id: 'intc',
    symbol: 'INTC',
    name: 'Intel Corporation',
    type: 'stock',
    price: 43.25,
    change: -0.75,
    changePercent: -1.70,
  },
  // Additional Tech Stocks (29 more)
  {
    id: 'orcl',
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    type: 'stock',
    price: 118.45,
    change: 2.15,
    changePercent: 1.85,
  },
  {
    id: 'adbe',
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    type: 'stock',
    price: 528.30,
    change: 8.50,
    changePercent: 1.64,
  },
  {
    id: 'csco',
    symbol: 'CSCO',
    name: 'Cisco Systems Inc.',
    type: 'stock',
    price: 52.80,
    change: 0.85,
    changePercent: 1.64,
  },
  {
    id: 'avgo',
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    type: 'stock',
    price: 1285.50,
    change: 28.50,
    changePercent: 2.27,
  },
  {
    id: 'txn',
    symbol: 'TXN',
    name: 'Texas Instruments',
    type: 'stock',
    price: 168.25,
    change: 2.45,
    changePercent: 1.48,
  },
  {
    id: 'qcom',
    symbol: 'QCOM',
    name: 'Qualcomm Inc.',
    type: 'stock',
    price: 145.80,
    change: 3.20,
    changePercent: 2.24,
  },
  {
    id: 'now',
    symbol: 'NOW',
    name: 'ServiceNow Inc.',
    type: 'stock',
    price: 742.50,
    change: 12.80,
    changePercent: 1.75,
  },
  {
    id: 'ibm',
    symbol: 'IBM',
    name: 'IBM Corporation',
    type: 'stock',
    price: 168.90,
    change: 1.85,
    changePercent: 1.11,
  },
  {
    id: 'uber',
    symbol: 'UBER',
    name: 'Uber Technologies',
    type: 'stock',
    price: 62.45,
    change: 1.85,
    changePercent: 3.05,
  },
  {
    id: 'shop',
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    type: 'stock',
    price: 78.50,
    change: 2.85,
    changePercent: 3.77,
  },
  {
    id: 'snow',
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    type: 'stock',
    price: 165.20,
    change: 4.50,
    changePercent: 2.80,
  },
  {
    id: 'pltr',
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    type: 'stock',
    price: 21.85,
    change: 0.95,
    changePercent: 4.54,
  },
  {
    id: 'coin',
    symbol: 'COIN',
    name: 'Coinbase Global',
    type: 'stock',
    price: 148.50,
    change: 8.50,
    changePercent: 6.07,
  },
  {
    id: 'spot',
    symbol: 'SPOT',
    name: 'Spotify Technology',
    type: 'stock',
    price: 285.40,
    change: 5.85,
    changePercent: 2.09,
  },
  {
    id: 'sq',
    symbol: 'SQ',
    name: 'Block Inc.',
    type: 'stock',
    price: 68.25,
    change: 2.15,
    changePercent: 3.25,
  },
  {
    id: 'pypl',
    symbol: 'PYPL',
    name: 'PayPal Holdings',
    type: 'stock',
    price: 62.80,
    change: 1.45,
    changePercent: 2.36,
  },
  {
    id: 'twlo',
    symbol: 'TWLO',
    name: 'Twilio Inc.',
    type: 'stock',
    price: 68.50,
    change: 1.85,
    changePercent: 2.78,
  },
  {
    id: 'docu',
    symbol: 'DOCU',
    name: 'DocuSign Inc.',
    type: 'stock',
    price: 58.25,
    change: 1.25,
    changePercent: 2.19,
  },
  {
    id: 'zm',
    symbol: 'ZM',
    name: 'Zoom Video',
    type: 'stock',
    price: 68.40,
    change: 1.15,
    changePercent: 1.71,
  },
  {
    id: 'roku',
    symbol: 'ROKU',
    name: 'Roku Inc.',
    type: 'stock',
    price: 68.25,
    change: 2.45,
    changePercent: 3.72,
  },
  {
    id: 'net',
    symbol: 'NET',
    name: 'Cloudflare Inc.',
    type: 'stock',
    price: 85.40,
    change: 2.85,
    changePercent: 3.45,
  },
  {
    id: 'ddog',
    symbol: 'DDOG',
    name: 'Datadog Inc.',
    type: 'stock',
    price: 128.50,
    change: 4.25,
    changePercent: 3.42,
  },
  {
    id: 'mdb',
    symbol: 'MDB',
    name: 'MongoDB Inc.',
    type: 'stock',
    price: 385.20,
    change: 12.50,
    changePercent: 3.35,
  },
  {
    id: 'crwd',
    symbol: 'CRWD',
    name: 'CrowdStrike Holdings',
    type: 'stock',
    price: 285.40,
    change: 8.50,
    changePercent: 3.07,
  },
  {
    id: 'zs',
    symbol: 'ZS',
    name: 'Zscaler Inc.',
    type: 'stock',
    price: 195.80,
    change: 5.85,
    changePercent: 3.08,
  },
  {
    id: 'panw',
    symbol: 'PANW',
    name: 'Palo Alto Networks',
    type: 'stock',
    price: 315.40,
    change: 8.25,
    changePercent: 2.69,
  },
  {
    id: 'okta',
    symbol: 'OKTA',
    name: 'Okta Inc.',
    type: 'stock',
    price: 98.50,
    change: 2.85,
    changePercent: 2.98,
  },
  {
    id: 'wday',
    symbol: 'WDAY',
    name: 'Workday Inc.',
    type: 'stock',
    price: 265.80,
    change: 5.45,
    changePercent: 2.09,
  },
  {
    id: 'veev',
    symbol: 'VEEV',
    name: 'Veeva Systems',
    type: 'stock',
    price: 195.40,
    change: 3.85,
    changePercent: 2.01,
  },
  // Financial Stocks
  {
    id: 'jpm',
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'stock',
    price: 172.45,
    change: 1.85,
    changePercent: 1.08,
  },
  {
    id: 'v',
    symbol: 'V',
    name: 'Visa Inc.',
    type: 'stock',
    price: 275.80,
    change: 2.15,
    changePercent: 0.79,
  },
  {
    id: 'ma',
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    type: 'stock',
    price: 452.30,
    change: 3.80,
    changePercent: 0.85,
  },
  {
    id: 'bac',
    symbol: 'BAC',
    name: 'Bank of America',
    type: 'stock',
    price: 35.45,
    change: 0.45,
    changePercent: 1.29,
  },
  {
    id: 'wfc',
    symbol: 'WFC',
    name: 'Wells Fargo & Co.',
    type: 'stock',
    price: 48.25,
    change: 0.65,
    changePercent: 1.37,
  },
  {
    id: 'gs',
    symbol: 'GS',
    name: 'Goldman Sachs Group',
    type: 'stock',
    price: 385.40,
    change: 5.85,
    changePercent: 1.54,
  },
  {
    id: 'ms',
    symbol: 'MS',
    name: 'Morgan Stanley',
    type: 'stock',
    price: 92.50,
    change: 1.25,
    changePercent: 1.37,
  },
  // Healthcare Stocks
  {
    id: 'unh',
    symbol: 'UNH',
    name: 'UnitedHealth Group',
    type: 'stock',
    price: 528.40,
    change: 4.85,
    changePercent: 0.93,
  },
  {
    id: 'jnj',
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    type: 'stock',
    price: 158.25,
    change: 1.45,
    changePercent: 0.92,
  },
  {
    id: 'pfe',
    symbol: 'PFE',
    name: 'Pfizer Inc.',
    type: 'stock',
    price: 28.45,
    change: -0.35,
    changePercent: -1.22,
  },
  {
    id: 'mrna',
    symbol: 'MRNA',
    name: 'Moderna Inc.',
    type: 'stock',
    price: 98.50,
    change: 3.85,
    changePercent: 4.07,
  },
  {
    id: 'abbv',
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    type: 'stock',
    price: 172.80,
    change: 2.15,
    changePercent: 1.26,
  },
  {
    id: 'lly',
    symbol: 'LLY',
    name: 'Eli Lilly & Co.',
    type: 'stock',
    price: 752.40,
    change: 18.50,
    changePercent: 2.52,
  },
  // Consumer & Retail
  {
    id: 'wmt',
    symbol: 'WMT',
    name: 'Walmart Inc.',
    type: 'stock',
    price: 165.80,
    change: 1.25,
    changePercent: 0.76,
  },
  {
    id: 'cost',
    symbol: 'COST',
    name: 'Costco Wholesale',
    type: 'stock',
    price: 725.40,
    change: 8.50,
    changePercent: 1.19,
  },
  {
    id: 'hd',
    symbol: 'HD',
    name: 'Home Depot Inc.',
    type: 'stock',
    price: 358.25,
    change: 4.85,
    changePercent: 1.37,
  },
  {
    id: 'low',
    symbol: 'LOW',
    name: "Lowe's Companies",
    type: 'stock',
    price: 225.40,
    change: 2.85,
    changePercent: 1.28,
  },
  {
    id: 'tgt',
    symbol: 'TGT',
    name: 'Target Corporation',
    type: 'stock',
    price: 142.80,
    change: 1.45,
    changePercent: 1.03,
  },
  {
    id: 'sbux',
    symbol: 'SBUX',
    name: 'Starbucks Corporation',
    type: 'stock',
    price: 98.50,
    change: 1.25,
    changePercent: 1.29,
  },
  {
    id: 'mcd',
    symbol: 'MCD',
    name: "McDonald's Corporation",
    type: 'stock',
    price: 295.40,
    change: 2.85,
    changePercent: 0.97,
  },
  {
    id: 'ko',
    symbol: 'KO',
    name: 'Coca-Cola Company',
    type: 'stock',
    price: 62.45,
    change: 0.45,
    changePercent: 0.73,
  },
  {
    id: 'pep',
    symbol: 'PEP',
    name: 'PepsiCo Inc.',
    type: 'stock',
    price: 172.80,
    change: 1.25,
    changePercent: 0.73,
  },
  {
    id: 'dis',
    symbol: 'DIS',
    name: 'Walt Disney Company',
    type: 'stock',
    price: 108.50,
    change: 2.45,
    changePercent: 2.31,
  },
  {
    id: 'nke',
    symbol: 'NKE',
    name: 'Nike Inc.',
    type: 'stock',
    price: 98.25,
    change: 1.85,
    changePercent: 1.92,
  },
  // Energy & Industrial
  {
    id: 'xom',
    symbol: 'XOM',
    name: 'Exxon Mobil Corp.',
    type: 'stock',
    price: 108.50,
    change: -1.85,
    changePercent: -1.68,
  },
  {
    id: 'cvx',
    symbol: 'CVX',
    name: 'Chevron Corporation',
    type: 'stock',
    price: 152.40,
    change: -2.25,
    changePercent: -1.46,
  },
  {
    id: 'ba',
    symbol: 'BA',
    name: 'Boeing Company',
    type: 'stock',
    price: 218.50,
    change: 4.85,
    changePercent: 2.27,
  },
  {
    id: 'cat',
    symbol: 'CAT',
    name: 'Caterpillar Inc.',
    type: 'stock',
    price: 295.80,
    change: 4.25,
    changePercent: 1.46,
  },
  {
    id: 'de',
    symbol: 'DE',
    name: 'Deere & Company',
    type: 'stock',
    price: 398.50,
    change: 5.85,
    changePercent: 1.49,
  },
  // ==========================================
  // ETFs (20+)
  // ==========================================
  {
    id: 'spy',
    symbol: 'SPY',
    name: 'SPDR S&P 500 ETF',
    type: 'etf',
    price: 478.25,
    change: 2.85,
    changePercent: 0.60,
  },
  {
    id: 'qqq',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    type: 'etf',
    price: 405.90,
    change: 4.20,
    changePercent: 1.05,
  },
  {
    id: 'iwm',
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    type: 'etf',
    price: 198.45,
    change: -1.20,
    changePercent: -0.60,
  },
  {
    id: 'dia',
    symbol: 'DIA',
    name: 'SPDR Dow Jones ETF',
    type: 'etf',
    price: 378.60,
    change: 1.45,
    changePercent: 0.38,
  },
  {
    id: 'voo',
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    type: 'etf',
    price: 439.80,
    change: 2.60,
    changePercent: 0.59,
  },
  {
    id: 'arkk',
    symbol: 'ARKK',
    name: 'ARK Innovation ETF',
    type: 'etf',
    price: 48.25,
    change: 1.85,
    changePercent: 3.99,
  },
  // Additional ETFs (14 more)
  {
    id: 'vti',
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market',
    type: 'etf',
    price: 245.80,
    change: 1.45,
    changePercent: 0.59,
  },
  {
    id: 'ivv',
    symbol: 'IVV',
    name: 'iShares Core S&P 500',
    type: 'etf',
    price: 482.50,
    change: 2.85,
    changePercent: 0.59,
  },
  {
    id: 'agg',
    symbol: 'AGG',
    name: 'iShares Core US Aggregate Bond',
    type: 'etf',
    price: 98.50,
    change: 0.15,
    changePercent: 0.15,
  },
  {
    id: 'ief',
    symbol: 'IEF',
    name: 'iShares 7-10 Year Treasury',
    type: 'etf',
    price: 95.80,
    change: 0.25,
    changePercent: 0.26,
  },
  {
    id: 'tlt',
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury',
    type: 'etf',
    price: 92.45,
    change: 0.45,
    changePercent: 0.49,
  },
  {
    id: 'gld',
    symbol: 'GLD',
    name: 'SPDR Gold Shares',
    type: 'etf',
    price: 185.40,
    change: 1.25,
    changePercent: 0.68,
  },
  {
    id: 'slv',
    symbol: 'SLV',
    name: 'iShares Silver Trust',
    type: 'etf',
    price: 21.85,
    change: 0.35,
    changePercent: 1.63,
  },
  {
    id: 'uso',
    symbol: 'USO',
    name: 'United States Oil Fund',
    type: 'etf',
    price: 72.50,
    change: -1.25,
    changePercent: -1.69,
  },
  {
    id: 'xlf',
    symbol: 'XLF',
    name: 'Financial Select SPDR',
    type: 'etf',
    price: 42.85,
    change: 0.45,
    changePercent: 1.06,
  },
  {
    id: 'xlk',
    symbol: 'XLK',
    name: 'Technology Select SPDR',
    type: 'etf',
    price: 195.40,
    change: 2.85,
    changePercent: 1.48,
  },
  {
    id: 'xle',
    symbol: 'XLE',
    name: 'Energy Select SPDR',
    type: 'etf',
    price: 85.40,
    change: -1.25,
    changePercent: -1.44,
  },
  {
    id: 'xlv',
    symbol: 'XLV',
    name: 'Health Care Select SPDR',
    type: 'etf',
    price: 142.80,
    change: 1.15,
    changePercent: 0.81,
  },
  {
    id: 'smh',
    symbol: 'SMH',
    name: 'VanEck Semiconductor ETF',
    type: 'etf',
    price: 195.80,
    change: 4.85,
    changePercent: 2.54,
  },
  {
    id: 'soxx',
    symbol: 'SOXX',
    name: 'iShares Semiconductor ETF',
    type: 'etf',
    price: 545.20,
    change: 12.50,
    changePercent: 2.35,
  },
  // ==========================================
  // FOREX PAIRS (15+)
  // ==========================================
  {
    id: 'eurusd',
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    type: 'forex',
    price: 1.0892,
    change: 0.0024,
    changePercent: 0.22,
  },
  {
    id: 'gbpusd',
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    type: 'forex',
    price: 1.2685,
    change: -0.0018,
    changePercent: -0.14,
  },
  {
    id: 'usdjpy',
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    type: 'forex',
    price: 148.52,
    change: 0.45,
    changePercent: 0.30,
  },
  {
    id: 'usdchf',
    symbol: 'USD/CHF',
    name: 'US Dollar / Swiss Franc',
    type: 'forex',
    price: 0.8745,
    change: -0.0012,
    changePercent: -0.14,
  },
  {
    id: 'audusd',
    symbol: 'AUD/USD',
    name: 'Australian Dollar / US Dollar',
    type: 'forex',
    price: 0.6582,
    change: 0.0035,
    changePercent: 0.53,
  },
  // Additional Forex (10 more)
  {
    id: 'usdcad',
    symbol: 'USD/CAD',
    name: 'US Dollar / Canadian Dollar',
    type: 'forex',
    price: 1.3485,
    change: 0.0028,
    changePercent: 0.21,
  },
  {
    id: 'nzdusd',
    symbol: 'NZD/USD',
    name: 'New Zealand Dollar / US Dollar',
    type: 'forex',
    price: 0.6145,
    change: 0.0018,
    changePercent: 0.29,
  },
  {
    id: 'eurgbp',
    symbol: 'EUR/GBP',
    name: 'Euro / British Pound',
    type: 'forex',
    price: 0.8585,
    change: 0.0012,
    changePercent: 0.14,
  },
  {
    id: 'eurjpy',
    symbol: 'EUR/JPY',
    name: 'Euro / Japanese Yen',
    type: 'forex',
    price: 161.85,
    change: 0.65,
    changePercent: 0.40,
  },
  {
    id: 'gbpjpy',
    symbol: 'GBP/JPY',
    name: 'British Pound / Japanese Yen',
    type: 'forex',
    price: 188.45,
    change: 0.85,
    changePercent: 0.45,
  },
  {
    id: 'usdhkd',
    symbol: 'USD/HKD',
    name: 'US Dollar / Hong Kong Dollar',
    type: 'forex',
    price: 7.8245,
    change: 0.0015,
    changePercent: 0.02,
  },
  {
    id: 'usdsgd',
    symbol: 'USD/SGD',
    name: 'US Dollar / Singapore Dollar',
    type: 'forex',
    price: 1.3425,
    change: 0.0018,
    changePercent: 0.13,
  },
  {
    id: 'usdmxn',
    symbol: 'USD/MXN',
    name: 'US Dollar / Mexican Peso',
    type: 'forex',
    price: 17.2450,
    change: -0.0850,
    changePercent: -0.49,
  },
  {
    id: 'usdzar',
    symbol: 'USD/ZAR',
    name: 'US Dollar / South African Rand',
    type: 'forex',
    price: 18.8540,
    change: 0.1250,
    changePercent: 0.67,
  },
  {
    id: 'usdtry',
    symbol: 'USD/TRY',
    name: 'US Dollar / Turkish Lira',
    type: 'forex',
    price: 32.4850,
    change: 0.1850,
    changePercent: 0.57,
  },
  // ==========================================
  // COMMODITIES (15+)
  // ==========================================
  {
    id: 'gold',
    symbol: 'XAU',
    name: 'Gold',
    type: 'commodity',
    price: 2024.50,
    change: 12.80,
    changePercent: 0.64,
  },
  {
    id: 'silver',
    symbol: 'XAG',
    name: 'Silver',
    type: 'commodity',
    price: 23.45,
    change: 0.28,
    changePercent: 1.21,
  },
  {
    id: 'oil',
    symbol: 'WTI',
    name: 'Crude Oil WTI',
    type: 'commodity',
    price: 78.25,
    change: -1.45,
    changePercent: -1.82,
  },
  {
    id: 'natgas',
    symbol: 'NG',
    name: 'Natural Gas',
    type: 'commodity',
    price: 2.85,
    change: 0.08,
    changePercent: 2.89,
  },
  {
    id: 'copper',
    symbol: 'HG',
    name: 'Copper',
    type: 'commodity',
    price: 3.82,
    change: 0.04,
    changePercent: 1.06,
  },
  // Additional Commodities (10 more)
  {
    id: 'platinum',
    symbol: 'XPT',
    name: 'Platinum',
    type: 'commodity',
    price: 985.40,
    change: 8.50,
    changePercent: 0.87,
  },
  {
    id: 'palladium',
    symbol: 'XPD',
    name: 'Palladium',
    type: 'commodity',
    price: 1025.80,
    change: -15.40,
    changePercent: -1.48,
  },
  {
    id: 'brent',
    symbol: 'BRENT',
    name: 'Brent Crude Oil',
    type: 'commodity',
    price: 82.45,
    change: -1.25,
    changePercent: -1.49,
  },
  {
    id: 'wheat',
    symbol: 'ZW',
    name: 'Wheat',
    type: 'commodity',
    price: 585.40,
    change: 4.85,
    changePercent: 0.84,
  },
  {
    id: 'corn',
    symbol: 'ZC',
    name: 'Corn',
    type: 'commodity',
    price: 445.80,
    change: 2.45,
    changePercent: 0.55,
  },
  {
    id: 'soybean',
    symbol: 'ZS',
    name: 'Soybeans',
    type: 'commodity',
    price: 1185.40,
    change: 8.50,
    changePercent: 0.72,
  },
  {
    id: 'coffee',
    symbol: 'KC',
    name: 'Coffee',
    type: 'commodity',
    price: 185.40,
    change: 3.85,
    changePercent: 2.12,
  },
  {
    id: 'sugar',
    symbol: 'SB',
    name: 'Sugar',
    type: 'commodity',
    price: 21.45,
    change: 0.35,
    changePercent: 1.66,
  },
  {
    id: 'cotton',
    symbol: 'CT',
    name: 'Cotton',
    type: 'commodity',
    price: 78.25,
    change: 0.85,
    changePercent: 1.10,
  },
  {
    id: 'aluminum',
    symbol: 'ALI',
    name: 'Aluminum',
    type: 'commodity',
    price: 2245.80,
    change: 18.50,
    changePercent: 0.83,
  },
];

// Get asset icon based on type
export function getAssetIcon(type: Asset['type']): string {
  switch (type) {
    case 'crypto':
      return '₿';
    case 'stock':
      return '📈';
    case 'etf':
      return '📊';
    case 'forex':
      return '💱';
    case 'commodity':
      return '🏆';
    default:
      return '💰';
  }
}

// Format price based on asset type
export function formatPrice(price: number, type: Asset['type']): string {
  if (type === 'forex') {
    return price.toFixed(4);
  }
  if (price < 1) {
    return price.toFixed(4);
  }
  if (price < 100) {
    return price.toFixed(2);
  }
  return price.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
