import { Asset } from './types';

export const INITIAL_CASH = 10000;

export const ASSETS: Asset[] = [
  // Tech Stocks
  {
    id: 'tsla',
    symbol: 'TSLA',
    name: 'Tesla Inc.',
    type: 'stock',
    price: 248.50,
    change: 12.30,
    changePercent: 5.2,
  },
  {
    id: 'aapl',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    type: 'stock',
    price: 178.25,
    change: -2.10,
    changePercent: -1.2,
  },
  {
    id: 'nvda',
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    type: 'stock',
    price: 485.90,
    change: 8.75,
    changePercent: 1.8,
  },
  {
    id: 'msft',
    symbol: 'MSFT',
    name: 'Microsoft Corporation',
    type: 'stock',
    price: 378.50,
    change: 3.20,
    changePercent: 0.9,
  },
  {
    id: 'amzn',
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    type: 'stock',
    price: 142.60,
    change: -1.80,
    changePercent: -1.2,
  },
  {
    id: 'meta',
    symbol: 'META',
    name: 'Meta Platforms Inc.',
    type: 'stock',
    price: 312.40,
    change: 5.60,
    changePercent: 1.8,
  },
  {
    id: 'googl',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    type: 'stock',
    price: 138.75,
    change: 2.15,
    changePercent: 1.6,
  },
  {
    id: 'nflx',
    symbol: 'NFLX',
    name: 'Netflix Inc.',
    type: 'stock',
    price: 445.20,
    change: -8.30,
    changePercent: -1.8,
  },
  // Financial & Other Sectors
  {
    id: 'jpm',
    symbol: 'JPM',
    name: 'JPMorgan Chase & Co.',
    type: 'stock',
    price: 154.85,
    change: 1.25,
    changePercent: 0.8,
  },
  {
    id: 'v',
    symbol: 'V',
    name: 'Visa Inc.',
    type: 'stock',
    price: 245.60,
    change: 3.40,
    changePercent: 1.4,
  },
  {
    id: 'jnj',
    symbol: 'JNJ',
    name: 'Johnson & Johnson',
    type: 'stock',
    price: 158.30,
    change: -0.85,
    changePercent: -0.5,
  },
  {
    id: 'pg',
    symbol: 'PG',
    name: 'Procter & Gamble Co.',
    type: 'stock',
    price: 162.45,
    change: 0.95,
    changePercent: 0.6,
  },
  {
    id: 'ko',
    symbol: 'KO',
    name: 'The Coca-Cola Company',
    type: 'stock',
    price: 61.20,
    change: 0.35,
    changePercent: 0.6,
  },
  {
    id: 'dis',
    symbol: 'DIS',
    name: 'The Walt Disney Company',
    type: 'stock',
    price: 96.55,
    change: -1.45,
    changePercent: -1.5,
  },
  // Energy Sector
  {
    id: 'xom',
    symbol: 'XOM',
    name: 'Exxon Mobil Corporation',
    type: 'stock',
    price: 105.40,
    change: 2.15,
    changePercent: 2.1,
  },
  {
    id: 'cvx',
    symbol: 'CVX',
    name: 'Chevron Corporation',
    type: 'stock',
    price: 148.90,
    change: 1.85,
    changePercent: 1.3,
  },
  // Healthcare Sector
  {
    id: 'unh',
    symbol: 'UNH',
    name: 'UnitedHealth Group Inc.',
    type: 'stock',
    price: 485.20,
    change: -3.40,
    changePercent: -0.7,
  },
  {
    id: 'pfe',
    symbol: 'PFE',
    name: 'Pfizer Inc.',
    type: 'stock',
    price: 28.75,
    change: 0.45,
    changePercent: 1.6,
  },
  {
    id: 'abbv',
    symbol: 'ABBV',
    name: 'AbbVie Inc.',
    type: 'stock',
    price: 157.60,
    change: 2.30,
    changePercent: 1.5,
  },
  // Consumer & Retail
  {
    id: 'wmt',
    symbol: 'WMT',
    name: 'Walmart Inc.',
    type: 'stock',
    price: 168.40,
    change: 1.25,
    changePercent: 0.8,
  },
  {
    id: 'hd',
    symbol: 'HD',
    name: 'The Home Depot Inc.',
    type: 'stock',
    price: 312.85,
    change: -2.60,
    changePercent: -0.8,
  },
  {
    id: 'mcd',
    symbol: 'MCD',
    name: "McDonald's Corporation",
    type: 'stock',
    price: 285.40,
    change: 3.15,
    changePercent: 1.1,
  },
  {
    id: 'nke',
    symbol: 'NKE',
    name: 'Nike Inc.',
    type: 'stock',
    price: 98.30,
    change: -1.90,
    changePercent: -1.9,
  },
  {
    id: 'sbux',
    symbol: 'SBUX',
    name: 'Starbucks Corporation',
    type: 'stock',
    price: 94.20,
    change: 0.85,
    changePercent: 0.9,
  },
  // Finance & Banking
  {
    id: 'bac',
    symbol: 'BAC',
    name: 'Bank of America Corporation',
    type: 'stock',
    price: 33.45,
    change: 0.65,
    changePercent: 2.0,
  },
  {
    id: 'gs',
    symbol: 'GS',
    name: 'The Goldman Sachs Group Inc.',
    type: 'stock',
    price: 382.50,
    change: 4.20,
    changePercent: 1.1,
  },
  {
    id: 'ma',
    symbol: 'MA',
    name: 'Mastercard Incorporated',
    type: 'stock',
    price: 412.30,
    change: 5.80,
    changePercent: 1.4,
  },
  {
    id: 'c',
    symbol: 'C',
    name: 'Citigroup Inc.',
    type: 'stock',
    price: 54.20,
    change: -0.85,
    changePercent: -1.5,
  },
  // Industrial & Manufacturing
  {
    id: 'ba',
    symbol: 'BA',
    name: 'The Boeing Company',
    type: 'stock',
    price: 192.40,
    change: -3.20,
    changePercent: -1.6,
  },
  {
    id: 'cat',
    symbol: 'CAT',
    name: 'Caterpillar Inc.',
    type: 'stock',
    price: 285.60,
    change: 2.40,
    changePercent: 0.8,
  },
  {
    id: 'ge',
    symbol: 'GE',
    name: 'General Electric Company',
    type: 'stock',
    price: 128.75,
    change: 1.95,
    changePercent: 1.5,
  },
  // Tech & Semiconductors
  {
    id: 'amd',
    symbol: 'AMD',
    name: 'Advanced Micro Devices Inc.',
    type: 'stock',
    price: 142.80,
    change: 3.60,
    changePercent: 2.6,
  },
  {
    id: 'intc',
    symbol: 'INTC',
    name: 'Intel Corporation',
    type: 'stock',
    price: 43.25,
    change: -0.75,
    changePercent: -1.7,
  },
  {
    id: 'crm',
    symbol: 'CRM',
    name: 'Salesforce Inc.',
    type: 'stock',
    price: 264.90,
    change: 4.50,
    changePercent: 1.7,
  },
  {
    id: 'orcl',
    symbol: 'ORCL',
    name: 'Oracle Corporation',
    type: 'stock',
    price: 112.40,
    change: 1.80,
    changePercent: 1.6,
  },
  {
    id: 'adbe',
    symbol: 'ADBE',
    name: 'Adobe Inc.',
    type: 'stock',
    price: 582.30,
    change: -5.20,
    changePercent: -0.9,
  },
  // Telecom & Media
  {
    id: 't',
    symbol: 'T',
    name: 'AT&T Inc.',
    type: 'stock',
    price: 17.85,
    change: 0.25,
    changePercent: 1.4,
  },
  {
    id: 'vz',
    symbol: 'VZ',
    name: 'Verizon Communications Inc.',
    type: 'stock',
    price: 40.65,
    change: -0.35,
    changePercent: -0.9,
  },
  {
    id: 'cmcsa',
    symbol: 'CMCSA',
    name: 'Comcast Corporation',
    type: 'stock',
    price: 42.90,
    change: 0.55,
    changePercent: 1.3,
  },
  // More Tech & Software
  {
    id: 'snap',
    symbol: 'SNAP',
    name: 'Snap Inc.',
    type: 'stock',
    price: 15.40,
    change: 0.85,
    changePercent: 5.8,
  },
  {
    id: 'uber',
    symbol: 'UBER',
    name: 'Uber Technologies Inc.',
    type: 'stock',
    price: 62.35,
    change: -1.25,
    changePercent: -1.96,
  },
  {
    id: 'lyft',
    symbol: 'LYFT',
    name: 'Lyft Inc.',
    type: 'stock',
    price: 12.80,
    change: 0.45,
    changePercent: 3.6,
  },
  {
    id: 'shop',
    symbol: 'SHOP',
    name: 'Shopify Inc.',
    type: 'stock',
    price: 68.90,
    change: 2.40,
    changePercent: 3.6,
  },
  {
    id: 'sq',
    symbol: 'SQ',
    name: 'Block Inc.',
    type: 'stock',
    price: 78.25,
    change: 1.95,
    changePercent: 2.6,
  },
  {
    id: 'pypl',
    symbol: 'PYPL',
    name: 'PayPal Holdings Inc.',
    type: 'stock',
    price: 62.40,
    change: -0.85,
    changePercent: -1.3,
  },
  {
    id: 'zoom',
    symbol: 'ZM',
    name: 'Zoom Video Communications Inc.',
    type: 'stock',
    price: 68.75,
    change: 1.20,
    changePercent: 1.8,
  },
  {
    id: 'docu',
    symbol: 'DOCU',
    name: 'DocuSign Inc.',
    type: 'stock',
    price: 54.30,
    change: -1.45,
    changePercent: -2.6,
  },
  {
    id: 'twlo',
    symbol: 'TWLO',
    name: 'Twilio Inc.',
    type: 'stock',
    price: 67.80,
    change: 2.15,
    changePercent: 3.3,
  },
  {
    id: 'spot',
    symbol: 'SPOT',
    name: 'Spotify Technology SA',
    type: 'stock',
    price: 182.45,
    change: 3.90,
    changePercent: 2.2,
  },
  {
    id: 'pins',
    symbol: 'PINS',
    name: 'Pinterest Inc.',
    type: 'stock',
    price: 28.60,
    change: 0.75,
    changePercent: 2.7,
  },
  {
    id: 'snow',
    symbol: 'SNOW',
    name: 'Snowflake Inc.',
    type: 'stock',
    price: 175.30,
    change: 4.60,
    changePercent: 2.7,
  },
  {
    id: 'ddog',
    symbol: 'DDOG',
    name: 'Datadog Inc.',
    type: 'stock',
    price: 112.90,
    change: 2.35,
    changePercent: 2.1,
  },
  {
    id: 'net',
    symbol: 'NET',
    name: 'Cloudflare Inc.',
    type: 'stock',
    price: 78.40,
    change: 1.85,
    changePercent: 2.4,
  },
  {
    id: 'team',
    symbol: 'TEAM',
    name: 'Atlassian Corporation',
    type: 'stock',
    price: 195.60,
    change: 3.20,
    changePercent: 1.7,
  },
  {
    id: 'now',
    symbol: 'NOW',
    name: 'ServiceNow Inc.',
    type: 'stock',
    price: 658.90,
    change: 8.45,
    changePercent: 1.3,
  },
  // Growth & Innovation Stocks
  {
    id: 'pltr',
    symbol: 'PLTR',
    name: 'Palantir Technologies Inc.',
    type: 'stock',
    price: 18.75,
    change: 0.95,
    changePercent: 5.3,
  },
  {
    id: 'rivn',
    symbol: 'RIVN',
    name: 'Rivian Automotive Inc.',
    type: 'stock',
    price: 14.20,
    change: -0.65,
    changePercent: -4.4,
  },
  {
    id: 'lcid',
    symbol: 'LCID',
    name: 'Lucid Group Inc.',
    type: 'stock',
    price: 3.45,
    change: 0.12,
    changePercent: 3.6,
  },
  {
    id: 'rblx',
    symbol: 'RBLX',
    name: 'Roblox Corporation',
    type: 'stock',
    price: 38.90,
    change: 1.45,
    changePercent: 3.9,
  },
  {
    id: 'coin',
    symbol: 'COIN',
    name: 'Coinbase Global Inc.',
    type: 'stock',
    price: 152.30,
    change: 6.80,
    changePercent: 4.7,
  },
  {
    id: 'hood',
    symbol: 'HOOD',
    name: 'Robinhood Markets Inc.',
    type: 'stock',
    price: 12.85,
    change: 0.55,
    changePercent: 4.5,
  },
  {
    id: 'sofi',
    symbol: 'SOFI',
    name: 'SoFi Technologies Inc.',
    type: 'stock',
    price: 8.90,
    change: 0.35,
    changePercent: 4.1,
  },
  {
    id: 'roku',
    symbol: 'ROKU',
    name: 'Roku Inc.',
    type: 'stock',
    price: 68.45,
    change: 2.15,
    changePercent: 3.2,
  },
  // Semiconductors & Hardware
  {
    id: 'asml',
    symbol: 'ASML',
    name: 'ASML Holding NV',
    type: 'stock',
    price: 785.40,
    change: 12.60,
    changePercent: 1.6,
  },
  {
    id: 'mu',
    symbol: 'MU',
    name: 'Micron Technology Inc.',
    type: 'stock',
    price: 92.35,
    change: 2.45,
    changePercent: 2.7,
  },
  {
    id: 'avgo',
    symbol: 'AVGO',
    name: 'Broadcom Inc.',
    type: 'stock',
    price: 1145.60,
    change: 18.90,
    changePercent: 1.7,
  },
  {
    id: 'qcom',
    symbol: 'QCOM',
    name: 'Qualcomm Inc.',
    type: 'stock',
    price: 148.75,
    change: 3.20,
    changePercent: 2.2,
  },
  {
    id: 'txn',
    symbol: 'TXN',
    name: 'Texas Instruments Inc.',
    type: 'stock',
    price: 168.90,
    change: 1.85,
    changePercent: 1.1,
  },
  {
    id: 'amat',
    symbol: 'AMAT',
    name: 'Applied Materials Inc.',
    type: 'stock',
    price: 178.30,
    change: 4.15,
    changePercent: 2.4,
  },
  {
    id: 'lrcx',
    symbol: 'LRCX',
    name: 'Lam Research Corporation',
    type: 'stock',
    price: 825.40,
    change: 14.25,
    changePercent: 1.8,
  },
  // Automotive
  {
    id: 'f',
    symbol: 'F',
    name: 'Ford Motor Company',
    type: 'stock',
    price: 12.45,
    change: 0.25,
    changePercent: 2.1,
  },
  {
    id: 'gm',
    symbol: 'GM',
    name: 'General Motors Company',
    type: 'stock',
    price: 38.90,
    change: -0.65,
    changePercent: -1.6,
  },
  {
    id: 'tm',
    symbol: 'TM',
    name: 'Toyota Motor Corporation',
    type: 'stock',
    price: 178.60,
    change: 2.40,
    changePercent: 1.4,
  },
  // More Healthcare & Biotech
  {
    id: 'mrk',
    symbol: 'MRK',
    name: 'Merck & Co. Inc.',
    type: 'stock',
    price: 112.85,
    change: 1.45,
    changePercent: 1.3,
  },
  {
    id: 'lly',
    symbol: 'LLY',
    name: 'Eli Lilly and Company',
    type: 'stock',
    price: 582.40,
    change: 8.90,
    changePercent: 1.6,
  },
  {
    id: 'bmy',
    symbol: 'BMY',
    name: 'Bristol-Myers Squibb Company',
    type: 'stock',
    price: 52.30,
    change: -0.45,
    changePercent: -0.9,
  },
  {
    id: 'gild',
    symbol: 'GILD',
    name: 'Gilead Sciences Inc.',
    type: 'stock',
    price: 78.90,
    change: 1.25,
    changePercent: 1.6,
  },
  {
    id: 'amgn',
    symbol: 'AMGN',
    name: 'Amgen Inc.',
    type: 'stock',
    price: 288.45,
    change: 3.60,
    changePercent: 1.3,
  },
  {
    id: 'mdlz',
    symbol: 'MDLZ',
    name: 'Mondelez International Inc.',
    type: 'stock',
    price: 72.85,
    change: 0.55,
    changePercent: 0.8,
  },
  {
    id: 'biib',
    symbol: 'BIIB',
    name: 'Biogen Inc.',
    type: 'stock',
    price: 268.90,
    change: -2.45,
    changePercent: -0.9,
  },
  {
    id: 'regn',
    symbol: 'REGN',
    name: 'Regeneron Pharmaceuticals Inc.',
    type: 'stock',
    price: 895.60,
    change: 12.35,
    changePercent: 1.4,
  },
  {
    id: 'vrtx',
    symbol: 'VRTX',
    name: 'Vertex Pharmaceuticals Inc.',
    type: 'stock',
    price: 412.80,
    change: 6.90,
    changePercent: 1.7,
  },
  // More Consumer & Retail
  {
    id: 'cost',
    symbol: 'COST',
    name: 'Costco Wholesale Corporation',
    type: 'stock',
    price: 628.90,
    change: 4.85,
    changePercent: 0.8,
  },
  {
    id: 'tgt',
    symbol: 'TGT',
    name: 'Target Corporation',
    type: 'stock',
    price: 142.30,
    change: -1.65,
    changePercent: -1.1,
  },
  {
    id: 'low',
    symbol: 'LOW',
    name: "Lowe's Companies Inc.",
    type: 'stock',
    price: 228.45,
    change: 2.90,
    changePercent: 1.3,
  },
  {
    id: 'tjx',
    symbol: 'TJX',
    name: 'The TJX Companies Inc.',
    type: 'stock',
    price: 94.60,
    change: 0.85,
    changePercent: 0.9,
  },
  {
    id: 'pep',
    symbol: 'PEP',
    name: 'PepsiCo Inc.',
    type: 'stock',
    price: 168.75,
    change: 1.35,
    changePercent: 0.8,
  },
  {
    id: 'cl',
    symbol: 'CL',
    name: 'Colgate-Palmolive Company',
    type: 'stock',
    price: 82.40,
    change: 0.45,
    changePercent: 0.5,
  },
  {
    id: 'ul',
    symbol: 'UL',
    name: 'Unilever PLC',
    type: 'stock',
    price: 56.90,
    change: 0.35,
    changePercent: 0.6,
  },
  {
    id: 'pm',
    symbol: 'PM',
    name: 'Philip Morris International Inc.',
    type: 'stock',
    price: 98.45,
    change: 1.25,
    changePercent: 1.3,
  },
  // Airlines & Travel
  {
    id: 'aal',
    symbol: 'AAL',
    name: 'American Airlines Group Inc.',
    type: 'stock',
    price: 14.85,
    change: 0.45,
    changePercent: 3.1,
  },
  {
    id: 'dal',
    symbol: 'DAL',
    name: 'Delta Air Lines Inc.',
    type: 'stock',
    price: 42.30,
    change: 1.15,
    changePercent: 2.8,
  },
  {
    id: 'ual',
    symbol: 'UAL',
    name: 'United Airlines Holdings Inc.',
    type: 'stock',
    price: 48.90,
    change: 1.45,
    changePercent: 3.1,
  },
  {
    id: 'luv',
    symbol: 'LUV',
    name: 'Southwest Airlines Co.',
    type: 'stock',
    price: 28.75,
    change: 0.65,
    changePercent: 2.3,
  },
  {
    id: 'mar',
    symbol: 'MAR',
    name: 'Marriott International Inc.',
    type: 'stock',
    price: 218.60,
    change: 3.45,
    changePercent: 1.6,
  },
  {
    id: 'bkng',
    symbol: 'BKNG',
    name: 'Booking Holdings Inc.',
    type: 'stock',
    price: 3245.80,
    change: 42.30,
    changePercent: 1.3,
  },
  // More Finance & Insurance
  {
    id: 'ms',
    symbol: 'MS',
    name: 'Morgan Stanley',
    type: 'stock',
    price: 88.45,
    change: 1.85,
    changePercent: 2.1,
  },
  {
    id: 'wfc',
    symbol: 'WFC',
    name: 'Wells Fargo & Company',
    type: 'stock',
    price: 48.90,
    change: 0.95,
    changePercent: 2.0,
  },
  {
    id: 'axp',
    symbol: 'AXP',
    name: 'American Express Company',
    type: 'stock',
    price: 182.45,
    change: 2.65,
    changePercent: 1.5,
  },
  {
    id: 'schw',
    symbol: 'SCHW',
    name: 'The Charles Schwab Corporation',
    type: 'stock',
    price: 68.75,
    change: 1.25,
    changePercent: 1.9,
  },
  {
    id: 'blk',
    symbol: 'BLK',
    name: 'BlackRock Inc.',
    type: 'stock',
    price: 785.30,
    change: 9.85,
    changePercent: 1.3,
  },
  {
    id: 'aig',
    symbol: 'AIG',
    name: 'American International Group Inc.',
    type: 'stock',
    price: 68.90,
    change: 0.75,
    changePercent: 1.1,
  },
  {
    id: 'met',
    symbol: 'MET',
    name: 'MetLife Inc.',
    type: 'stock',
    price: 72.35,
    change: 0.85,
    changePercent: 1.2,
  },
  // Real Estate & REITs
  {
    id: 'amt',
    symbol: 'AMT',
    name: 'American Tower Corporation',
    type: 'stock',
    price: 198.45,
    change: 2.35,
    changePercent: 1.2,
  },
  {
    id: 'pld',
    symbol: 'PLD',
    name: 'Prologis Inc.',
    type: 'stock',
    price: 128.90,
    change: 1.65,
    changePercent: 1.3,
  },
  {
    id: 'sbac',
    symbol: 'SBAC',
    name: 'SBA Communications Corporation',
    type: 'stock',
    price: 228.75,
    change: 3.45,
    changePercent: 1.5,
  },
  // More Industrials
  {
    id: 'ups',
    symbol: 'UPS',
    name: 'United Parcel Service Inc.',
    type: 'stock',
    price: 158.40,
    change: 2.15,
    changePercent: 1.4,
  },
  {
    id: 'fdx',
    symbol: 'FDX',
    name: 'FedEx Corporation',
    type: 'stock',
    price: 248.90,
    change: 3.85,
    changePercent: 1.6,
  },
  {
    id: 'de',
    symbol: 'DE',
    name: 'Deere & Company',
    type: 'stock',
    price: 398.60,
    change: 5.45,
    changePercent: 1.4,
  },
  {
    id: 'lmt',
    symbol: 'LMT',
    name: 'Lockheed Martin Corporation',
    type: 'stock',
    price: 448.90,
    change: -2.35,
    changePercent: -0.5,
  },
  {
    id: 'rtx',
    symbol: 'RTX',
    name: 'RTX Corporation',
    type: 'stock',
    price: 98.45,
    change: 1.25,
    changePercent: 1.3,
  },
  {
    id: 'hon',
    symbol: 'HON',
    name: 'Honeywell International Inc.',
    type: 'stock',
    price: 198.75,
    change: 2.45,
    changePercent: 1.2,
  },
  {
    id: 'mmm',
    symbol: 'MMM',
    name: '3M Company',
    type: 'stock',
    price: 108.90,
    change: -0.85,
    changePercent: -0.8,
  },
  // Materials & Chemicals
  {
    id: 'linde',
    symbol: 'LIN',
    name: 'Linde plc',
    type: 'stock',
    price: 418.60,
    change: 4.35,
    changePercent: 1.0,
  },
  {
    id: 'apd',
    symbol: 'APD',
    name: 'Air Products and Chemicals Inc.',
    type: 'stock',
    price: 288.45,
    change: 3.15,
    changePercent: 1.1,
  },
  {
    id: 'dow',
    symbol: 'DOW',
    name: 'Dow Inc.',
    type: 'stock',
    price: 54.80,
    change: 0.65,
    changePercent: 1.2,
  },
  {
    id: 'dd',
    symbol: 'DD',
    name: 'DuPont de Nemours Inc.',
    type: 'stock',
    price: 78.35,
    change: 0.95,
    changePercent: 1.2,
  },
  // Utilities
  {
    id: 'nee',
    symbol: 'NEE',
    name: 'NextEra Energy Inc.',
    type: 'stock',
    price: 62.45,
    change: 0.85,
    changePercent: 1.4,
  },
  {
    id: 'duke',
    symbol: 'DUK',
    name: 'Duke Energy Corporation',
    type: 'stock',
    price: 98.75,
    change: 0.45,
    changePercent: 0.5,
  },
  {
    id: 'so',
    symbol: 'SO',
    name: 'The Southern Company',
    type: 'stock',
    price: 72.30,
    change: 0.35,
    changePercent: 0.5,
  },
  // More Crypto (like Binance)
  {
    id: 'dot',
    symbol: 'DOT',
    name: 'Polkadot',
    type: 'crypto',
    price: 7.85,
    change: 0.35,
    changePercent: 4.7,
  },
  {
    id: 'avax',
    symbol: 'AVAX',
    name: 'Avalanche',
    type: 'crypto',
    price: 36.90,
    change: 1.85,
    changePercent: 5.3,
  },
  {
    id: 'matic',
    symbol: 'MATIC',
    name: 'Polygon',
    type: 'crypto',
    price: 0.89,
    change: 0.04,
    changePercent: 4.7,
  },
  {
    id: 'link',
    symbol: 'LINK',
    name: 'Chainlink',
    type: 'crypto',
    price: 14.75,
    change: 0.65,
    changePercent: 4.6,
  },
  {
    id: 'uni',
    symbol: 'UNI',
    name: 'Uniswap',
    type: 'crypto',
    price: 6.45,
    change: 0.28,
    changePercent: 4.5,
  },
  {
    id: 'atom',
    symbol: 'ATOM',
    name: 'Cosmos',
    type: 'crypto',
    price: 10.25,
    change: 0.45,
    changePercent: 4.6,
  },
  {
    id: 'ltc',
    symbol: 'LTC',
    name: 'Litecoin',
    type: 'crypto',
    price: 72.80,
    change: 2.40,
    changePercent: 3.4,
  },
  {
    id: 'algo',
    symbol: 'ALGO',
    name: 'Algorand',
    type: 'crypto',
    price: 0.18,
    change: 0.01,
    changePercent: 5.9,
  },
  {
    id: 'xlm',
    symbol: 'XLM',
    name: 'Stellar',
    type: 'crypto',
    price: 0.13,
    change: 0.006,
    changePercent: 4.8,
  },
  {
    id: 'doge',
    symbol: 'DOGE',
    name: 'Dogecoin',
    type: 'crypto',
    price: 0.09,
    change: 0.004,
    changePercent: 4.7,
  },
  {
    id: 'shib',
    symbol: 'SHIB',
    name: 'Shiba Inu',
    type: 'crypto',
    price: 0.000009,
    change: 0.0000004,
    changePercent: 4.7,
  },
  // More ETFs for Sector Diversification
  {
    id: 'voo',
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    type: 'etf',
    price: 412.85,
    change: 1.95,
    changePercent: 0.5,
  },
  {
    id: 'vti',
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    type: 'etf',
    price: 238.60,
    change: 1.25,
    changePercent: 0.5,
  },
  {
    id: 'vea',
    symbol: 'VEA',
    name: 'Vanguard FTSE Developed Markets ETF',
    type: 'etf',
    price: 48.90,
    change: 0.35,
    changePercent: 0.7,
  },
  {
    id: 'vwo',
    symbol: 'VWO',
    name: 'Vanguard FTSE Emerging Markets ETF',
    type: 'etf',
    price: 42.35,
    change: 0.55,
    changePercent: 1.3,
  },
  {
    id: 'xlk',
    symbol: 'XLK',
    name: 'Technology Select Sector SPDR Fund',
    type: 'etf',
    price: 185.40,
    change: 2.85,
    changePercent: 1.6,
  },
  {
    id: 'xlv',
    symbol: 'XLV',
    name: 'Health Care Select Sector SPDR Fund',
    type: 'etf',
    price: 142.90,
    change: 0.95,
    changePercent: 0.7,
  },
  {
    id: 'xlf',
    symbol: 'XLF',
    name: 'Financial Select Sector SPDR Fund',
    type: 'etf',
    price: 38.75,
    change: 0.45,
    changePercent: 1.2,
  },
  {
    id: 'xle',
    symbol: 'XLE',
    name: 'Energy Select Sector SPDR Fund',
    type: 'etf',
    price: 82.40,
    change: 1.25,
    changePercent: 1.5,
  },
  {
    id: 'xli',
    symbol: 'XLI',
    name: 'Industrial Select Sector SPDR Fund',
    type: 'etf',
    price: 112.85,
    change: 1.15,
    changePercent: 1.0,
  },
  {
    id: 'xlre',
    symbol: 'XLRE',
    name: 'Real Estate Select Sector SPDR Fund',
    type: 'etf',
    price: 38.90,
    change: 0.35,
    changePercent: 0.9,
  },
  {
    id: 'arkk',
    symbol: 'ARKK',
    name: 'ARK Innovation ETF',
    type: 'etf',
    price: 48.75,
    change: 1.85,
    changePercent: 3.9,
  },
  {
    id: 'vgt',
    symbol: 'VGT',
    name: 'Vanguard Information Technology ETF',
    type: 'etf',
    price: 482.30,
    change: 6.45,
    changePercent: 1.4,
  },
  {
    id: 'vb',
    symbol: 'VB',
    name: 'Vanguard Small-Cap ETF',
    type: 'etf',
    price: 218.45,
    change: -0.85,
    changePercent: -0.4,
  },
  {
    id: 'vig',
    symbol: 'VIG',
    name: 'Vanguard Dividend Appreciation ETF',
    type: 'etf',
    price: 168.90,
    change: 0.95,
    changePercent: 0.6,
  },
  // ETFs
  {
    id: 'spy',
    symbol: 'SPY',
    name: 'S&P 500 ETF Trust',
    type: 'etf',
    price: 448.30,
    change: 2.10,
    changePercent: 0.5,
  },
  {
    id: 'qqq',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    type: 'etf',
    price: 385.40,
    change: 4.20,
    changePercent: 1.1,
  },
  {
    id: 'dia',
    symbol: 'DIA',
    name: 'SPDR Dow Jones Industrial Average ETF',
    type: 'etf',
    price: 378.90,
    change: 1.85,
    changePercent: 0.5,
  },
  {
    id: 'iwm',
    symbol: 'IWM',
    name: 'iShares Russell 2000 ETF',
    type: 'etf',
    price: 195.75,
    change: -1.20,
    changePercent: -0.6,
  },
  {
    id: 'tlt',
    symbol: 'TLT',
    name: 'iShares 20+ Year Treasury Bond ETF',
    type: 'etf',
    price: 92.15,
    change: -0.45,
    changePercent: -0.5,
  },
  // Cryptocurrencies
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    type: 'crypto',
    price: 43250.00,
    change: 1820.00,
    changePercent: 4.4,
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    type: 'crypto',
    price: 2280.50,
    change: -65.30,
    changePercent: -2.8,
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    type: 'crypto',
    price: 98.75,
    change: 5.20,
    changePercent: 5.6,
  },
  {
    id: 'ada',
    symbol: 'ADA',
    name: 'Cardano',
    type: 'crypto',
    price: 0.52,
    change: 0.03,
    changePercent: 6.1,
  },
  {
    id: 'bnb',
    symbol: 'BNB',
    name: 'Binance Coin',
    type: 'crypto',
    price: 312.80,
    change: -8.40,
    changePercent: -2.6,
  },
  {
    id: 'xrp',
    symbol: 'XRP',
    name: 'Ripple',
    type: 'crypto',
    price: 0.61,
    change: 0.02,
    changePercent: 3.4,
  },
  // Commodities
  {
    id: 'xau',
    symbol: 'XAU',
    name: 'Gold',
    type: 'commodity',
    price: 2025.80,
    change: 8.40,
    changePercent: 0.4,
  },
  {
    id: 'xag',
    symbol: 'XAG',
    name: 'Silver',
    type: 'commodity',
    price: 24.15,
    change: 0.35,
    changePercent: 1.5,
  },
  {
    id: 'wti',
    symbol: 'WTI',
    name: 'Crude Oil',
    type: 'commodity',
    price: 78.45,
    change: -1.25,
    changePercent: -1.6,
  },
  {
    id: 'ng',
    symbol: 'NG',
    name: 'Natural Gas',
    type: 'commodity',
    price: 2.85,
    change: 0.08,
    changePercent: 2.9,
  },
];
