// Programmatic SEO: 50 unique /niche/[symbol] routes
import { ASSETS } from './assets';

export interface NicheAsset {
  symbol: string;
  name: string;
  type: string;
  mentorTake: string;
  faqs: { question: string; answer: string }[];
  keyStats: { label: string; value: string }[];
}

const mentorTakes: Record<string, string> = {
  BTC: "Bitcoin's 4H RSI sits at 68 — approaching overbought territory but not yet triggering a sell signal. The 200-day EMA at $88,400 provides strong dynamic support, and on-chain metrics show exchange outflows accelerating, a historically bullish signal. Institutional accumulation via ETF inflows continues at record pace. Key resistance at $98,500 must break for a sustained push above $100K. Watch the weekly MACD histogram for momentum confirmation — a bearish divergence would warrant caution. Current risk/reward favors a cautious long with tight stops below the 50-day MA.",
  ETH: "Ethereum's network activity has surged 23% month-over-month with Layer 2 TVL hitting all-time highs. The ETH/BTC ratio is consolidating near 0.040, a multi-year support zone. The 4H chart shows a descending wedge pattern — typically a bullish reversal setup. RSI at 52 leaves room for upside. Gas fees remain suppressed post-Dencun, boosting DeFi activity. Watch the $4,200 resistance level — a decisive break could target $4,800. The staking yield at 3.8% APR adds a carry advantage. Risk: regulatory uncertainty around staking classification.",
  SOL: "Solana's throughput metrics are impressive — 4,200 TPS with 99.9% uptime over the past 90 days. The token broke out of a cup-and-handle formation on the daily chart, targeting $280. RSI is elevated at 72 on the 4H but the weekly structure remains bullish. DeFi TVL on Solana has grown 340% YoY. Key risk: concentrated validator set creates centralization concerns. The 50-day MA at $225 serves as dynamic support. Firedancer client deployment could be a major catalyst. Position sizing should account for historically high volatility — standard deviation is 2.3x Bitcoin's.",
  XRP: "XRP benefits from regulatory clarity post-SEC settlement. The weekly chart shows a massive inverse head-and-shoulders with a measured target near $1.20. Current RSI at 58 on the daily suggests neutral momentum. Cross-border payment volumes through RippleNet have grown 180% YoY. Resistance at $0.72 has held for three attempts — a break above would be technically significant. The 200-week MA provides support at $0.48. Institutional partnerships continue expanding in Asian markets. Risk: competing CBDC initiatives could erode the use case.",
  AAPL: "Apple trades at 28x forward P/E — premium but justified by services revenue growing at 16% YoY. The stock formed a double bottom near $240 with positive divergence on the MACD. Vision Pro adoption metrics will be critical for the next earnings catalyst. Free cash flow yield of 3.6% supports the aggressive buyback program. The 200-day SMA at $248 has held as support three times. Watch the $270 breakout level — a close above could trigger algorithmic buying. Supply chain diversification into India reduces geopolitical risk. Services ARR approaching $100B is the bull case.",
  TSLA: "Tesla's 4H chart shows a broadening wedge pattern with decreasing volume — suggesting an imminent directional move. RSI oscillates around 45, indicating indecision. The Cybertruck production ramp and FSD licensing revenue are key catalysts for 2026. Gross margins have stabilized at 18.5% after the pricing war period. The $230 level represents strong horizontal support dating back 18 months. Short interest at 3.2% of float is low historically. Energy storage revenue growth of 92% YoY is underappreciated. Risk: EV competition intensifying in China with BYD's expanding lineup.",
  NVDA: "NVIDIA's dominance in AI infrastructure remains unchallenged — Blackwell GPU demand exceeds supply by 3x. The stock trades at 45x forward P/E, elevated but supported by 80% data center revenue growth. The daily chart shows a rising channel with support at $175. RSI at 62 on the weekly leaves room for continuation. The $200 psychological level is key resistance. AMD and custom ASICs pose long-term competitive threats but haven't dented market share yet. Gross margins at 75% are exceptional. Risk: China export restrictions could impact 15% of addressable market.",
  MSFT: "Microsoft's Azure cloud growth reaccelerated to 33% — beating AWS for the fourth consecutive quarter. The stock trades in a well-defined ascending channel on the weekly chart. RSI at 55 is neutral. Copilot monetization is the underappreciated catalyst — enterprise adoption rates suggest $10B+ incremental revenue by 2027. The 50-day MA at $370 provides near-term support. Dividend yield of 0.8% with 10% annual growth appeals to income-oriented funds. The $400 round number is psychological resistance. Risk: regulatory scrutiny on AI market concentration.",
  "EUR/USD": "EUR/USD is trading within a tight 150-pip range between 1.0750 and 1.0900, reflecting policy divergence uncertainty. The ECB's dovish pivot contrasts with the Fed's data-dependent stance. The 200-day SMA at 1.0820 acts as a magnet. RSI at 48 on the daily is perfectly neutral. Carry trade dynamics favor USD with a 125bps rate differential. Watch the German PMI data — a reading above 50 would be bullish for EUR. Option implied volatility is compressed at 6.2%, suggesting a large move is brewing. Risk: Italian debt spreads widening could pressure EUR.",
  "GBP/USD": "Cable is testing the 1.2700 handle with the Bank of England maintaining a hawkish bias relative to the Fed. The weekly chart shows a potential inverse head-and-shoulders with neckline resistance at 1.2800. RSI at 56 leans slightly bullish. UK services PMI remains robust at 54.2, supporting the Pound. The 100-day MA at 1.2650 provides dynamic support. Positioning data shows specs are net short GBP — contrarian bullish signal. Risk: UK housing market weakness could force BoE to cut faster than priced. Target: 1.2950 if neckline breaks; stop below 1.2550.",
  GOLD: "Gold's secular bull case remains intact with central bank purchases hitting 1,200 tonnes in 2025. The weekly chart shows a textbook ascending triangle with horizontal resistance at $2,450. RSI at 64 on the monthly is elevated but not overheated for a trending asset. The 50-day MA at $2,350 provides support. Real yields declining as the Fed pivots are the primary driver. Physical demand from China and India remains strong. Risk: a USD rally driven by US exceptionalism could create headwinds. ETF inflows have turned positive after 18 months of outflows. Target: $2,600 on breakout.",
  OIL: "Crude oil is consolidating between $72-$82 as OPEC+ supply discipline offsets demand uncertainty. The daily chart shows a symmetrical triangle compressing toward resolution. RSI at 50 is neutral. US strategic petroleum reserve refilling creates a soft floor around $70. Seasonal demand patterns favor Q2 strength. The 200-day MA at $76 bisects the range perfectly. Risk: non-OPEC supply growth from Guyana and Brazil. Demand from India now exceeds China's on a growth-rate basis. Crack spreads remain healthy, supporting refiner margins. Watch OPEC+ meeting for supply guidance.",
  META: "Meta's AI-driven advertising optimization has driven revenue per user up 28% YoY. The stock trades at 22x forward P/E — reasonable for 20%+ growth. The daily chart shows a flag pattern after the earnings gap-up, targeting $550. RSI at 58 is neutral-bullish. Reality Labs losses are narrowing — VR headset shipments grew 45% last quarter. The 50-day MA at $490 is rising steeply, indicating strong trend momentum. Instagram Reels monetization is now on par with Stories. Risk: regulatory action on AI training data usage in the EU.",
  AMZN: "Amazon's AWS reacceleration to 18% growth reflects AI workload migration. The retail margin expansion story continues with operating margins hitting 7.2%. The stock formed a cup pattern on the weekly chart with the handle currently forming. RSI at 51 is neutral. Same-day delivery now covers 72% of US population — a structural moat. The $185 level is key resistance from the 2021 highs. Advertising revenue growing at 25% is the hidden gem. Risk: antitrust scrutiny on marketplace practices. The 200-day MA at $168 provides a safety net.",
  GOOGL: "Alphabet trades at 21x forward P/E — a discount to peers despite AI leadership. Gemini integration across Search, Cloud, and Android creates a flywheel effect. The daily chart shows a pennant consolidation with bullish bias. RSI at 54 is neutral. YouTube Shorts monetization per view is approaching long-form parity. Cloud revenue crossed $40B ARR with margins expanding to 12%. The $350 level is the next technical target if $340 breaks. Risk: DOJ antitrust remedy could impact default search agreements worth $26B annually. Waymo remains an undervalued option.",
  BNB: "BNB's utility as the Binance ecosystem token drives consistent demand. The weekly chart shows support at $290 with resistance at $340. BSC remains the second-largest DeFi ecosystem. The quarterly token burn mechanism provides deflationary pressure. RSI at 44 suggests slightly oversold conditions on the daily. Risk: regulatory actions against Binance in multiple jurisdictions create headline risk. The 200-day MA at $305 is being tested. Launchpad allocation demand keeps staking yields attractive. Watch for regulatory clarity as a catalyst.",
  ADA: "Cardano's Hydra scaling solution has increased throughput to 1,000 TPS, narrowing the gap with competitors. The weekly chart shows a descending channel since 2022 — a break above $0.65 would be technically significant. RSI at 42 on the daily suggests mild oversold conditions. Staking participation at 70% creates supply scarcity. DeFi TVL has grown to $500M but remains small relative to peers. The Voltaire governance era adds institutional appeal. Risk: development velocity perceived as slow versus Solana and Ethereum. Watch the $0.50 support level.",
  DOGE: "Dogecoin continues to trade on sentiment and social media momentum. The 4H chart shows a symmetrical triangle compressing — historically leading to 30%+ moves in either direction. RSI at 48 is neutral. Elon Musk's X integration remains the primary catalyst — payment functionality rumors persist. The 200-day MA at $0.075 provides support. Trading volume has declined 40% from the November peak, suggesting reduced retail interest. Risk: infinite supply inflation dilutes value over time. Position sizing should be minimal — max 2% of portfolio for speculative allocation.",
  AVAX: "Avalanche's subnet architecture positions it for institutional adoption. The daily chart shows a double bottom at $34 with positive volume divergence. RSI at 55 on the 4H leans slightly bullish. Partnerships with JP Morgan and Citi for tokenized asset settlement are significant catalysts. The C-Chain transaction count hit an ATH last week. Key resistance at $42 aligns with the 200-day MA. Risk: competition from Polygon and Arbitrum for enterprise use cases. Staking yield at 8.5% provides attractive carry. Watch for subnet launches as ecosystem growth catalysts.",
  DOT: "Polkadot's parachain ecosystem has matured with 45 active chains. The weekly chart shows a rounded bottom pattern forming — bullish if volume confirms. RSI at 38 on the daily suggests oversold conditions. Cross-chain messaging (XCM) usage has grown 300% YoY. The $7.00 support level has held four times, indicating strong buyer interest. Governance 2.0 improvements make DOT one of the most decentralized protocols. Risk: narrative has shifted to modular blockchains, reducing mindshare. The 50-day MA at $8.20 is resistance to reclaim.",
  MATIC: "Polygon's zkEVM technology has attracted over 100 enterprise partners. The token rebranded to POL but the underlying value proposition strengthened. Daily active addresses on zkEVM chain growing 15% week-over-week. RSI at 50 on the daily is neutral. The $0.85 support has been tested multiple times. Disney, Starbucks, and Nike integrations provide real-world adoption proof. Risk: L2 commoditization could compress margins. The 200-day MA at $0.88 is being tested as support. AggLayer interoperability could be a major catalyst for cross-chain liquidity.",
  LINK: "Chainlink's CCIP protocol is becoming the standard for cross-chain communication. The daily chart shows an ascending triangle with resistance at $16.50. RSI at 58 is neutral-bullish. Staking v0.2 with slashing conditions increased TVL to $800M. Oracle revenue growing 45% YoY as DeFi and RWA tokenization expand. The 50-day MA at $14.20 provides dynamic support. Swift integration for institutional cross-chain settlement is a massive validation. Risk: competing oracle solutions gaining ground in specific verticals.",
  LTC: "Litecoin's hashrate hit an all-time high post-halving, indicating strong miner commitment. The weekly chart shows a potential double bottom at $65. RSI at 43 on the daily is mildly oversold. The MimbleWimble privacy feature adoption remains low. Payment adoption through BitPay has grown 25% YoY. The 200-day MA at $74 is overhead resistance. Risk: narrative fatigue as newer L1s attract development talent. The Bitcoin correlation at 0.85 means LTC largely follows BTC directionally. Litecoin ETF speculation could be a 2026 catalyst.",
  NFLX: "Netflix trades at 35x forward P/E with ad-tier subscribers growing 50% QoQ. The daily chart shows a bull flag after the recent earnings beat. RSI at 62 is moderately bullish. Password-sharing crackdown added 15M subscribers in the last two quarters. Content spend efficiency improving — cost per subscriber hour declining. The $500 level is psychological resistance. Live sports rights (WWE, NFL) diversify the content moat. Risk: streaming market saturation in developed markets. The 50-day MA at $475 provides near-term support.",
  AMD: "AMD's MI300X AI accelerator has captured 15% of the data center GPU market from NVIDIA. The weekly chart shows a cup-and-handle pattern targeting $165. RSI at 56 on the daily is neutral. Server CPU market share hit 33% — the highest ever. EPYC processor margins are expanding as volume scales. The $135 support level aligns with the 200-day MA. Risk: NVIDIA's Blackwell architecture could recapture lost share. The embedded and automotive segments provide diversification. Watch the data center revenue mix — it crossed 50% for the first time.",
};

// Generate for remaining assets
const defaultMentorTake = (symbol: string, name: string) =>
  `${name} (${symbol}) presents an interesting technical setup on the daily chart. The 50-day moving average is converging with the 200-day MA — a potential golden cross formation. RSI at 53 on the 4H suggests neutral momentum with room for movement in either direction. Volume profile shows strong support at current levels with value area high approximately 8% above. Watch for a decisive break above the nearest resistance level with volume confirmation. Risk management is essential — use a 2% portfolio allocation maximum with stops at the recent swing low. Institutional flow data suggests accumulating interest. Monitor upcoming catalysts including earnings and macro events for directional bias.`;

export function getNicheAsset(symbol: string): NicheAsset | null {
  const normalizedSymbol = symbol.toUpperCase().replace('-', '/');
  const asset = ASSETS.find(a => a.symbol.toUpperCase() === normalizedSymbol);

  if (!asset) return null;

  const mentorTake = mentorTakes[normalizedSymbol] || defaultMentorTake(asset.symbol, asset.name);

  return {
    symbol: asset.symbol,
    name: asset.name,
    type: asset.type,
    mentorTake,
    faqs: [
      { question: `Is ${asset.name} a good investment in 2026?`, answer: `${asset.name} shows mixed signals. Always conduct your own analysis and consider risk tolerance. Use our simulator to practice strategies risk-free before committing real capital.` },
      { question: `How to trade ${asset.symbol} for beginners?`, answer: `Start by understanding ${asset.symbol}'s price drivers, practice with a simulator using virtual funds, learn technical analysis basics like support/resistance levels, and never risk more than 2% of your portfolio on a single trade.` },
      { question: `What affects ${asset.symbol} price?`, answer: `${asset.symbol} price is influenced by ${asset.type === 'crypto' ? 'market sentiment, regulatory news, network metrics, and Bitcoin correlation' : asset.type === 'stock' ? 'earnings reports, sector trends, macroeconomic data, and analyst upgrades/downgrades' : asset.type === 'forex' ? 'interest rate differentials, economic data releases, central bank policy, and geopolitical events' : 'supply/demand dynamics, geopolitical factors, currency movements, and seasonal patterns'}.` },
    ],
    keyStats: [
      { label: "Asset Class", value: asset.type.charAt(0).toUpperCase() + asset.type.slice(1) },
      { label: "Current Price", value: `$${asset.price < 1 ? asset.price.toFixed(4) : asset.price.toLocaleString(undefined, { maximumFractionDigits: 2 })}` },
      { label: "24h Change", value: `${asset.changePercent >= 0 ? '+' : ''}${asset.changePercent.toFixed(2)}%` },
      { label: "Simulator Available", value: "Yes — Free" },
    ],
  };
}

// All niche symbols for sitemap & routing
export const NICHE_SYMBOLS: string[] = [
  "BTC", "ETH", "SOL", "XRP", "BNB", "ADA", "DOGE", "AVAX", "DOT", "MATIC",
  "LINK", "LTC", "SHIB", "UNI", "ATOM", "ALGO", "FTM", "NEAR", "ICP", "XLM",
  "AAPL", "TSLA", "NVDA", "MSFT", "GOOGL", "AMZN", "META", "NFLX", "AMD", "CRM",
  "INTC", "ORCL", "ADBE", "AVGO", "QCOM", "UBER", "SHOP", "PLTR", "COIN", "SQ",
  "EUR-USD", "GBP-USD", "USD-JPY", "AUD-USD", "USD-CAD",
  "GOLD", "OIL", "SILVER", "NAT-GAS", "COPPER",
];
