import assert from 'node:assert/strict';
import { addPortfolioSnapshot, getPortfolioHistory, recordSnapshot } from '../src/lib/portfolioHistory';
import { calculateMaxDrawdown } from '../src/lib/portfolio';
import { getWeeklyRecap } from '../src/lib/weeklyRecap';
const store = new Map<string, string>();
Object.defineProperty(globalThis, 'localStorage', {value: {getItem: (key: string) => store.get(key) ?? null, setItem: (key: string, value: string) => store.set(key, value)}, configurable: true});
const legacy = JSON.stringify([{timestamp: new Date(), totalValue: 1000000, cash: 0, positionsValue: 1000000}, {timestamp: new Date(), totalValue: 1, cash: 0, positionsValue: 1}]);
store.set('tradesandbox_history', legacy);
assert.deepEqual(getPortfolioHistory(), []);
assert.equal(getWeeklyRecap().hasData, false);
assert.equal(calculateMaxDrawdown(), 0);
addPortfolioSnapshot({timestamp: new Date('2026-09-29T00:00:00Z'), cash: 100, positionsValue: 100, totalValue: 200});
addPortfolioSnapshot({timestamp: new Date('2026-09-29T01:00:00Z'), cash: 100, positionsValue: 60, totalValue: 160});
assert.equal(getPortfolioHistory().length, 2);
assert.equal(calculateMaxDrawdown(), 20);
assert.equal(store.get('tradesandbox_history'), legacy);
recordSnapshot(NaN, 100);
assert.equal(getPortfolioHistory().length, 2);
store.set('tradehq_observed_history_v1', '{unreadable');
assert.deepEqual(getPortfolioHistory(), []);
recordSnapshot(100, 100);
assert.equal(store.get('tradehq_observed_history_v1'), '{unreadable');
assert.equal(store.get('tradesandbox_history'), legacy);
console.log('History isolation, drawdown and data-preservation checks passed');
